name = "Dario Caricchio"
license = "MIT"
licenselink = "https://github.com/dariocaricchio/hugo-portfolio/blob/master/LICENSE"
description = "Portfolio Site"
homepage = "https://somrat.netlify.com" # TODO
tags = ['landing-page', 'fast', 'light', 'white', 'modern', 'dark', 'hugo-theme', 'hugo-templates', 'bootstrap', 'blog', 'responsive', 'clean', 'simple', 'creative', 'contact-form', 'custom-themes', 'mobile', 'minimalistic', 'pages', 'resume', 'portfolio', 'google analytics', 'customizable', 'flexbox', 'presentation', 'product', 'theme', 'typography']
features = ['bootstrap','responsive']
min_version = "0.60.0"

[author]
  name = "dariocaricchio"
  homepage = "https://somrat.netlify.com/" # TODO
